sudo: required 
services:
  - docker

before_install:
  - docker build -t hades42/dockerthing -f Dockerfile.dev .

script:
  - docker run -e CI=true hades42/dockerthing npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1" 
  app: "learndocker"
  env: "Learndocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-588551023804"
  bucket_path: "learndocker"
  branches:
    only:
      - main
